# Generated by Django 6.0.3 on 2026-03-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.IntegerField(choices=[(1, 'reading'), (2, 'grammar'), (3, 'speaking')]),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_lesson.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('variant_a', models.CharField(max_length=255)),
                ('variant_b', models.CharField(max_length=255)),
                ('variant_c', models.CharField(max_length=255)),
                ('variant_d', models.CharField(max_length=255)),
                ('task_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_lesson.test')),
            ],
        ),
    ]
