# Generated by Django 6.0.3 on 2026-03-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lesson', '0002_alter_lesson_type_test_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default='Some description', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_lesson.language'),
        ),
    ]
