# Generated by Django 6.0.3 on 2026-03-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lesson', '0004_alter_language_name_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_lesson.language'),
        ),
    ]
