# Generated by Django 6.0.4 on 2026-05-18 20:47

import core.lesson.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lesson', '0006_lesson_created_lesson_updated_solvedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=core.lesson.models.get_poster_upload_path),
        ),
    ]
