export const Common = {
    url: "remote-language-app-production.up.railway.app",
    networkErrorMsg: "Something went wrong. Try again later.",
    authErrorMsg: "You have to login first!",
    lines: {
        en: {
            title: {
                username: "Username",
                name: "Name",
                surname: "Surname",
                password: "Password",
                mainFeatures: "Main Features",
                feedbackPopUp: "Feedback",
                lessons: "LESSONS",
                categories: "CATEGORIES",
                languages: "LANGUAGES",
                authors: "AUTHORS",
                policy: "POLICY",
                deleteion: "Deletion",
                author: "Author",
                date: "Date",
                login: "Login",
                feedbackPage: "ADMIN",
                sortBy: "Sort by",
                lessonsBy: "Lessons by",
                comment: "Comment",
                comments: "Comments",
                test: "Test",
                of: "of",
                registration: "Registration",
            },
            message: {
                saved: "Saved successfully!",
            },
            placeholder: {
                commentInput: "Your comment...",
                feedbackInput: "Your feedback...",
                login: "Your username...",
                password: "Your password...",
                bio: "Your bio...",
                name: "Your name...",
                surname: "Your surname...",
                email: "Your email...",
            },
            button: {
                saveBtn: "Save",
                signIn: "Sign in",
                signUp: "Sign up",
                createLesson: "Create lesson",
                seeLessons: "See lessons",
                findTests: "Find tests",
                feedbackBtn: "Leave feedback",
                cancelBtn: "Cancel",
                sendBtn: "Save",
                deleteBtn: "Delete",
                studyBtn: "Study",
                loginBtn: "Login",
                show: "Show",
                hide: "Hide",
                blockBtn: "Block",
                unblockBtn: "Unblock",
                profileBtn: "Profile",
                nextBtn: "Next",
                prevBtn: "Prev",
                agreeBtn: "Accept",
                addCommentBtn: "Add comment",
                checkTestBtn: "Check test",
                registerBtn: "Registration",
            },
            error: {
                empty: "Please, fill this field!",
                testMin: "Test has to include at least 2 tasks!",
                testMax: "Test can contain no more than 10 tasks!",
                loginPassword: "Incorrect login or password!",
            },
            question: {
                lessonDelete: "Are you sure you want to delete this lesson?",
            },
            languages: {
                "en": "English",
                "gr": "German",
                "fr": "French",
                "ru": "Russian",
                "ch": "Chinese",
                "jp": "Japanese",
            },
            lessonLang: {
                "English": "English",
                "German": "German",
                "French": "French",
                "Russian": "Russian",
                "Chinese": "Chinese",
                "Japanese": "Japanese",
            },
            categories: {
                reading: "reading",
                grammar: "grammar",
                speaking: "speaking",
            },
            rating: {
                high: "High rating",
                low: "Low rating",
            },
            menu: {
                home: "Home",
                lessons: "Lessons",
                authors: "Authors",
                create: "Create",
                profile: "Profile",
                logout: "Logout",
                login: "Login",
                registration: "Registration",
                feedback: "Feedback",
            },
            home: {
                title: "Expand your horizons in terms of language learning",
                titleText: "Make it simple to learn foreign languages with our platform, which offers wide range of different lessons, practical tests, regular content updates and social communication with outher learners.",
                features: {
                    lessons: {
                        title: "Many lessons",
                        text: "We suggest many lessons of different languages on our platform. We believe that you'll definitely find something for yourself.",
                    },
                    tests: {
                        title: "Practical tests",
                        text: "Many lessons offers practical tests in addition to their contents. So you can start using your theoretical knowledge immediately.",
                    },
                    creation: {
                        title: "Ease of creation",
                        text: "Create new content easily and painless with our predefined layout. It'll give you a lot possibilities to express your creativity.",
                    },
                },
                policy: {
                    text: "By using the site, you agree to our privacy policy.",
                    call: "Read more.",
                },
                callToAction: {
                    title: "Start learning now",
                    text: "Quickly design your own lessons, find and solve somebody's else, share your opinion in the comment section, and express how much you've liked creator's content by liking it.\nDon't wait for a tomorrow, start now!",
                },
                feedback: {
                    title: "User's feedback",
                    question: "Have an opinion on our platform?",
                },
            },
            policy: {
                scope: {
                    title: "1. SCOPE AND PURPOSE",
                    body: "This Privacy and Cookie Policy explains how RLang ('we', 'us', 'our', or the 'Company') collects, processes, uses, and protects personal data from users ('you,' 'your', or 'User') of our language learning web application (the 'Service').",
                },
                basis: {
                    title: "2. LEGAL BASIS FOR PROCESSING",
                    body: "We process your personal data on the following legal grounds:",
                    items: [
                        "Performance of Contract: Processing your login credentials, name, surname, and email is necessary to provide you access to our Service and maintain your account.",
                        "Legitimate Interests: We may process data for security, fraud prevention, service improvement, and business analytics where such interests are not overridden by your rights.",
                        "Consent: Where required by law, we rely on your explicit consent for certain processing activities, particularly regarding cookies.",
                        "Legal Obligation: We process data to comply with applicable laws and regulations.",
                    ],
                },
                data: {
                    title: "3. PERSONAL DATA WE COLLECT",
                    body: "We collect and process the following personal data:",
                    items: [
                        "Login (Username) - Account creation and authentication",
                        "Password - Account security (encrypted/hashed)",
                        "Name & Surname - Personalization and identification",
                        "Email Address - Notifications, communication",
                        "IP Address - Security, fraud detection, service analytics",
                    ],
                },
                usage: {
                    title: "4. HOW WE USE YOUR DATA",
                    body: "We use your personal data for the following purposes:",
                    items: [
                        "Creating and managing your account",
                        "Providing, maintaining, and improving the Service",
                        "Sending service-related communications (e.g., password resets, updates)",
                        "Responding to your inquiries",
                        "Detecting and preventing fraud, abuse, and security incidents",
                        "Complying with legal obligations",
                    ],
                },
                sharing: {
                    title: "5. SHARING OF PERSONAL DATA",
                    body: "We do not sell, rent, or share your personal data with third parties for their marketing purposes. We may share your data in the following cases:",
                    items: [
                        "Service Providers: With processors who provide essential services (hosting, email, analytics) under data processing agreements",
                        "Legal Requirements: When required by law, court order, or government request",
                        "Business Transfers: In case of merger, acquisition, or sale of assets",
                        "User Consent: When you explicitly consent to sharing with specific third parties",
                    ],
                },
                transfers: {
                    title: "6. INTERNATIONAL DATA TRANSFERS",
                    body: "If your data is transferred outside the EU/EEA, we ensure adequate safeguards through:",
                    items: [
                        "Standard Contractual Clauses (SCCs)",
                        "Adequacy Decisions by the European Commission",
                        "Your explicit consent",
                    ],
                }
            }
        },
        gr: {
            title: {
                username: "Benutzernamen",
                name: "Name",
                surname: "Familienname",
                password: "Passwort",
                mainFeatures: "Hauptmerkmal",
                feedbackPopUp: "Feedback",
                lessons: "LEHREN",
                categories: "KATEGORIEN",
                languages: "SPRACHE",
                authors: "AUTOR",
                policy: "POLITIK",
                deleteion: "Löschung",
                author: "Autor",
                date: "Datum",
                login: "Login",
                feedbackPage: "ADMIN",
                sortBy: "Sortieren nach",
                lessonsBy: "Lektionen von",
                comment: "Kommentar",
                comments: "Kommentare",
                test: "Test",
                of: "von",
                registration: "Registrierung",
            },
            placeholder: {
                commentInput: "Ihr Kommentar...",
                feedbackInput: "Ihr Feedback...",
                login: "Ihr Benutzername...",
                password: "Ihr Passwort...",
                bio: "Deine Biografie...",
                name: "Ihr Name...",
                surname: "Ihr Nachname...",
                email: "Ihre email...",
            },
            message: {
                saved: "Erfolgreich gespeichert!",
            },
            button: {
                saveBtn: "Speichern",
                signIn: "Anmelden",
                signUp: "Registrierung",
                createLesson: "Lektion erstellen",
                seeLessons: "Feedback hinterlassen",
                findTests: "Tests finden",
                feedbackBtn: "Laisser des commentaires",
                cancelBtn: "Stornieren",
                sendBtn: "Speichern",
                deleteBtn: "Löschen",
                studyBtn: "Studie",
                loginBtn: "Login",
                show: "Karte",
                hide: "Verstecken",
                blockBtn: "Blockieren",
                unblockBtn: "Entsperren",
                profileBtn: "Profil",
                nextBtn: "Nächsten",
                prevBtn: "Vorherigen",
                agreeBtn: "Akzeptieren",
                lessonsBy: "Lessons by",
                addCommentBtn: "Kommentar hinzufügen",
                checkTestBtn: "Prüfungstest",
                registerBtn: "Registrierung",
            },
            error: {
                empty: "Bitte füllen Sie dieses Feld aus!",
                testMin: "Der Test muss mindestens 2 Aufgaben enthalten!",
                testMax: "Der Test kann nicht mehr als 10 Aufgaben enthalten!",
                loginPassword: "Falsches Login oder Passwort!",
            },
            question: {
                lessonDelete: "Sind Sie sicher, dass Sie diese Lektion löschen möchten?",
            },
            languages: {
                "en": "Englischsprachig",
                "gr": "Deutsch",
                "fr": "Französisch",
                "ru": "Russisch",
                "ch": "Chinesisch",
                "jp": "Japanisch",
            },
            lessonLang: {
                "English": "Englischsprachig",
                "German": "Deutsch",
                "French": "Französisch",
                "Russian": "Russisch",
                "Chinese": "Chinesisch",
                "Japanese": "Japanisch",
            },
            categories: {
                reading: "lesung",
                grammar: "grammatik",
                speaking: "sprechen",
            },
            rating: {
                high: "Hohe Bewertung",
                low: "Niedrige Bewertung",
            },
            menu: {
                home: "Startseite",
                lessons: "Lehren",
                authors: "Autor",
                create: "Erstellen",
                profile: "Profil",
                logout: "Abmelden",
                login: "Login",
                registration: "Registrierung",
                feedback: "Feedback",
            },
            home: {
                title: "Erweitern Sie Ihren Horizont in Bezug auf das Sprachenlernen",
                titleText: "Erleichtern Sie das Erlernen von Fremdsprachen mit unserer Plattform, die eine breite Palette verschiedener Lektionen, praktischer Tests und sozialer Kommunikation mit anderen Lernenden bietet.",
                features: {
                    lessons: {
                        title: "Viele Lektionen",
                        text: "Wir schlagen auf unserer Plattform viele Lektionen in verschiedenen Sprachen vor. Wir glauben, dass Sie auf jeden Fall etwas für sich finden werden.",
                    },
                    tests: {
                        title: "Praxistest",
                        text: "Viele Lektionen bieten zusätzlich zu ihren Inhalten praktische Tests an. So können Sie Ihr theoretisches Wissen sofort anwenden.",
                    },
                    creation: {
                        title: "Leichtigkeit der Schöpfung",
                        text: "Erstellen Sie neue Inhalte einfach und schmerzlos mit unserem vordefinierten Layout. Es gibt Ihnen viele Möglichkeiten, Ihre Kreativität auszudrücken.",
                    },
                },
                policy: {
                    text: "Durch die Nutzung der Website stimmen Sie unseren Datenschutzbestimmungen zu.",
                    call: "Lesen Sie mehr.",
                },
                callToAction: {
                    title: "Jetzt starten",
                    text: "Entwerfen Sie schnell Ihre eigenen Lektionen, finden und lösen Sie die von jemand anderem, teilen Sie Ihre Meinung im Kommentarbereich mit und drücken Sie aus, wie sehr Ihnen der Inhalt des Erstellers gefallen hat. Warte nicht auf ein Morgen, fang jetzt an!",
                },
                feedback: {
                    title: "Benutzer-Feedback",
                    question: "Haben Sie eine Meinung zu unserer Plattform?",
                },
            },
            policy: {
                scope: {
                    title: "1. GELTUNGSBEREICH UND ZWECK",
                    body: "Diese Datenschutz- und Cookie-Richtlinie erläutert, wie RLang ('wir', 'uns', 'unser' oder das 'Unternehmen') personenbezogene Daten von Nutzern ('Sie', 'Ihr' oder 'Nutzer') unserer Sprachlern-Webanwendung (der 'Dienst') erfasst, verarbeitet, nutzt und schützt.",
                },
                basis: {
                    title: "2. RECHTSGRUNDLAGE FÜR DIE VERARBEITUNG",
                    body: "Wir verarbeiten Ihre personenbezogenen Daten auf folgenden rechtlichen Grundlagen:",
                    items: [
                        "Vertragserfüllung: Die Verarbeitung Ihrer Anmeldedaten, Namen, Nachnames und E-Mail-Adresse ist erforderlich, um Ihnen Zugriff auf unseren Dienst zu gewähren und Ihr Konto zu verwalten.",
                        "Berechtigte Interessen: Wir verarbeiten Daten zum Schutz der Sicherheit, zur Betrugsprävention, Verbesserung des Dienstes und zur Geschäftsanalyse, soweit Ihre Rechte nicht überwiegen.",
                        "Einwilligung: Soweit gesetzlich erforderlich, stützen wir uns auf Ihre ausdrückliche Einwilligung, insbesondere für Cookies.",
                        "Rechtliche Verpflichtung: Wir verarbeiten Daten zur Einhaltung geltender Gesetze.",
                    ],
                },
                data: {
                    title: "3. ERFASSTE PERSONENBEZOGENE DATEN",
                    body: "Wir erfassen und verarbeiten folgende personenbezogene Daten:",
                    items: [
                        "Benutzername - Kontoerstellung und Authentifizierung",
                        "Passwort - Kontosicherheit (verschlüsselt/gehasht)",
                        "Name & Nachname - Personalisierung und Identifizierung",
                        "E-Mail-Adresse - Benachrichtigungen, Kommunikation",
                        "IP-Adresse - Sicherheit, Betrugserkennung, Service-Analyse",
                    ],
                },
                usage: {
                    title: "4. VERWENDUNG IHRER DATEN",
                    body: "Wir nutzen Ihre personenbezogenen Daten für folgende Zwecke:",
                    items: [
                        "Erstellung und Verwaltung Ihres Kontos",
                        "Bereitstellung, Wartung und Verbesserung des Dienstes",
                        "Versand von servicebezogenen Mitteilungen (z. B. Passwort-Zurücksetzen, Updates)",
                        "Beantwortung Ihrer Anfragen",
                        "Erkennung und Verhinderung von Betrug und Missbrauch",
                        "Einhaltung rechtlicher Verpflichtungen",
                    ],
                },
                sharing: {
                    title: "5. WEITERGABE IHRER DATEN",
                    body: "Wir verkaufen, vermieten oder geben Ihre personenbezogenen Daten nicht an Dritte zu Marketingzwecken weiter. Wir können Ihre Daten in folgenden Fällen offenlegen:",
                    items: [
                        "Dienstanbieter: An Anbieter, die wesentliche Dienste (Hosting, E-Mail, Analytik) erbringen, unter Datenverarbeitungsvereinbarungen",
                        "Rechtliche Anforderungen: Wenn gesetzlich erforderlich, durch Gerichtsbeschluss oder behördliche Anfrage",
                        "Geschäftsübergänge: Bei Fusion, Übernahme oder Veräußerung von Vermögenswerten",
                        "Nutzerzustimmung: Mit Ihrer ausdrücklichen Zustimmung",
                    ],
                },
                transfers: {
                    title: "6. INTERNATIONALE DATENTRANSFERS",
                    body: "Falls Ihre Daten außerhalb des EWR verarbeitet werden, sichern wir angemessene Schutzmaßnahmen durch:",
                    items: [
                        "Standardvertragsklauseln (SCC)",
                        "Angemessenheitsbeschlüsse der Europäischen Kommission",
                        "Ihre ausdrückliche Einwilligung",
                    ],
                },
            },
        },
        fr: {
            title: {
                username: "Nom d'utilisateur",
                name: "Nom",
                surname: "Nom de Famille",
                password: "Mot de Passe",
                mainFeatures: "Caractéristiques Principales",
                feedbackPopUp: "Commentaires",
                lessons: "LEÇONS",
                categories: "CATÉGORIES",
                languages: "LANGUES",
                authors: "AUTEURS",
                policy: "POLITIQUE",
                deleteion: "Suppression",
                author: "Auteur",
                date: "Date",
                login: "Connexion",
                feedbackPage: "ADMIN",
                sortBy: "Trier par",
                lessonsBy: "Leçons par",
                comment: "Commentaire",
                comments: "Commentaires",
                test: "Essai",
                of: "du",
                registration: "Inscription",
            },
            message: {
                saved: "Enregistré avec succès!",
            },
            placeholder: {
                commentInput: "Votre commentaire...",
                feedbackInput: "Vos commentaires...",
                login: "Votre nom d'utilisateur...",
                password: "Votre mot de passe...",
                bio: "Votre bio...",
                name: "Votre nom...",
                surname: "Your Votre nom de famille...",
                email: "Votre email...",
            },
            button: {
                saveBtn: "Sauvegarder",
                signIn: "Se connecter",
                signUp: "S'inscrire",
                createLesson: "Créer une leçon",
                seeLessons: "Voir les leçons",
                findTests: "Trouver des tests",
                feedbackBtn: "Laisser des commentaires",
                cancelBtn: "Annuler",
                sendBtn: "Sauvegarder",
                deleteBtn: "Supprimer",
                studyBtn: "Étude",
                loginBtn: "Connexion",
                show: "Afficher",
                hide: "Cacher",
                blockBtn: "Bloquer",
                unblockBtn: "Débloquer",
                profileBtn: "Profil",
                nextBtn: "Suivant",
                prevBtn: "Précédent",
                agreeBtn: "Accepter",
                addCommentBtn: "Ajouter un commentaire",
                checkTestBtn: "Essai de contrôle",
                registerBtn: "Inscription",
            },
            error: {
                empty: "Veuillez remplir ce champ!",
                testMin: "Le test doit inclure au moins 2 tâches!",
                testMax: "Le test ne peut pas contenir plus de 10 tâches!",
                loginPassword: "Identifiant ou mot de passe incorrect!",
            },
            question: {
                lessonDelete: "Êtes-vous sûr de vouloir supprimer cette leçon?",
            },
            languages: {
                "en": "Anglais",
                "gr": "Allemand",
                "fr": "Français",
                "ru": "Russe",
                "ch": "Chinois",
                "jp": "Japonais",
            },
            lessonLang: {
                "English": "Anglais",
                "German": "Allemand",
                "French": "Français",
                "Russian": "Russe",
                "Chinese": "Chinois",
                "Japanese": "Japonais",
            },
            categories: {
                reading: "lecture",
                grammar: "grammaire",
                speaking: "parler",
            },
            rating: {
                high: "Note élevée",
                low: "Note faible",
            },
            menu: {
                home: "Accueil",
                lessons: "Leçons",
                authors: "Auteurs",
                create: "Créer",
                profile: "Profil",
                logout: "Déconnexion",
                login: "Connexion",
                registration: "Inscription",
                feedback: "Commentaires",
            },
            home: {
                title: "Élargir les horizons en termes d'apprentissage des langues",
                titleText: "Simplifiez l'apprentissage des langues étrangères avec notre plateforme, qui propose un large éventail de leçons différentes, des tests pratiques une communication sociale avec les apprenants extérieurs.",
                features: {
                    lessons: {
                        title: "De nombreuses leçons",
                        text: "Nous suggérons de nombreuses leçons de différentes langues sur notre plateforme. Vous trouverez certainement quelque chose pour vous-même.",
                    },
                    tests: {
                        title: "Tests pratiques",
                        text: "Les leçons proposent des tests pratiques en plus de leur contenu. Vous pouvez donc commencer à utiliser vos nouvelles connaissances immédiatement.",
                    },
                    creation: {
                        title: "Facilité de création",
                        text: "Créez de nouveaux contenus facilement et sans douleur avec notre mise en page prédéfinie. Cela vous laissera beaucoup de possibilités d'exprimer votre créativité.",
                    },
                },
                policy: {
                    text: "En utilisant le site, vous acceptez notre politique de confidentialité.",
                    call: "En savoir plus.",
                },
                callToAction: {
                    title: "Commencez ici",
                    text: "Concevez rapidement vos propres leçons, trouvez et résolvez celles de quelqu'un d'autre, partagez votre opinion dans la section des commentaires et exprimez à quel point vous avez aimé le contenu du créateur. N'attendez pas demain, commencez maintenant!",
                },
                feedback: {
                    title: "Commentaires de l'utilisateur",
                    question: "Vous avez un avis sur notre plateforme?",
                },
            },
            policy: {
                    scope: {
                        title: "1. CHAMP D'APPLICATION ET OBJECTIF",
                        body: "Cette politique de confidentialité et de cookies explique comment RLang (« nous », « notre » ou « l'Entreprise ») collecte, traite, utilise et protège les données personnelles des utilisateurs (« vous », « votre » ou « Utilisateur ») de notre application web d'apprentissage des langues (le « Service »).",
                    },
                    basis: {
                        title: "2. BASE JURIDIQUE DU TRAITEMENT",
                        body: "Nous traitons vos données personnelles sur la base juridique suivante:",
                        items: [
                            "Exécution d'un contrat : Le traitement de vos identifiants de connexion, nom, prénom et adresse e-mail est nécessaire pour vous donner accès à notre Service et gérer votre compte.",
                            "Intérêts légitimes : Nous pouvons traiter des données pour la sécurité, la prévention de la fraude, l'amélioration du service et l'analyse commerciale lorsque ces intérêts ne sont pas dépassés par vos droits.",
                            "Consentement : Lorsque la loi l'exige, nous nous appuyons sur votre consentement explicite, notamment pour les cookies.",
                            "Obligation légale : Nous traitons les données pour nous conformer aux lois et réglementations applicables.",
                        ],
                    },
                    data: {
                        title: "3. DONNÉES PERSONNELLES QUE NOUS COLLECTONS",
                        body: "Nous collectons et traitons les données personnelles suivantes:",
                        items: [
                            "Identifiant de connexion (nom d'utilisateur) - Création et authentification de compte",
                            "Mot de passe - Sécurité du compte (chiffré/haché)",
                            "Nom et prénom - Personnalisation et identification",
                            "Adresse e-mail - notifications, communication",
                            "Adresse IP - Sécurité, détection de fraude, analyse du service",
                        ],
                    },
                    usage: {
                        title: "4. COMMENT NOUS UTILISONS VOS DONNÉES",
                        body: "Nous utilisons vos données personnelles pour les objectifs suivants:",
                        items: [
                            "Créer et gérer votre compte",
                            "Fournir, maintenir et améliorer le Service",
                            "Envoyer des communications liées au service (par exemple, réinitialisation de mot de passe, mises à jour)",
                            "Répondre à vos demandes",
                            "Détecter et prévenir la fraude, les abus et les incidents de sécurité",
                            "Respecter les obligations légales",
                        ],
                    },
                    sharing: {
                        title: "5. PARTAGE DE VOS DONNÉES",
                        body: "Nous ne vendons, ne louons ni ne partageons vos données personnelles avec des tiers à des fins marketing. Nous pouvons partager vos données dans les cas suivants:",
                        items: [
                            "Prestataires de services : Avec des fournisseurs qui fournissent des services essentiels (hébergement, e-mail, analytique) en vertu de contrats de traitement de données",
                            "Exigences légales : Lorsque la loi l'exige, par ordonnance judiciaire ou demande gouvernementale",
                            "Transferts d'activité : En cas de fusion, acquisition ou vente d'actifs",
                            "Consentement de l'utilisateur : Lorsque vous consentez explicitement à partager avec des tiers spécifiques",
                        ],
                    },
                    transfers: {
                        title: "6. TRANSFERTS INTERNATIONAUX DE DONNÉES",
                        body: "Si vos données sont transférées en dehors de l'UE/EEE, nous assurons des garanties adéquates par:",
                        items: [
                            "Des clauses contractuelles types (CCT)",
                            "Des décisions d'adéquation de la Commission européenne",
                            "Votre consentement explicite",
                        ],
                    },
                },
        },
        ru: {
            title: {
                username: "Логин",
                name: "Имя",
                surname: "Фамилия",
                password: "Пароль",
                mainFeatures: "Основные преимущества",
                feedbackPopUp: "Обратная связь",
                lessons: "УРОКИ",
                categories: "КАТЕГОРИИ",
                languages: "ЯЗЫКИ",
                authors: "АВТОРЫ",
                policy: "ПРАВИЛА",
                deleteion: "Удаление",
                author: "Автор",
                date: "Дата",
                login: "Авторизация",
                feedbackPage: "АДМИН",
                sortBy: "Сортировать по",
                lessonsBy: "Уроки от",
                comment: "Комментарий",
                comments: "Комментарии",
                test: "Тест",
                of: "из",
                registration: "Регистрация",
            },
            message: {
                saved: "Успешно сохранено!",
            },
            placeholder: {
                commentInput: "Ваш комментарий...",
                feedbackInput: "Ваш отзыв...",
                login: "Ваш логин...",
                password: "Ваш пароль...",
                bio: "Ваша биография...",
                name: "Ваше имя...",
                surname: "Ваша фамилия...",
                email: "Ваш email...",
            },
            button: {
                saveBtn: "Сохранить",
                signIn: "Вход",
                signUp: "Регистрация",
                createLesson: "Создать урок",
                seeLessons: "Все уроки",
                findTests: "Найти тест",
                feedbackBtn: "Оставить отзыв",
                cancelBtn: "Отмена",
                sendBtn: "Отправить",
                deleteBtn: "Удалить",
                studyBtn: "Изучить",
                loginBtn: "Войти",
                show: "Показать",
                hide: "Убрать",
                blockBtn: "Заблокировать",
                unblockBtn: "Разблокировать",
                profileBtn: "Профиль",
                nextBtn: "След",
                prevBtn: "Пред",
                agreeBtn: "Принять",
                addCommentBtn: "Добавить комментарий",
                checkTestBtn: "Проверить тест",
                of: "из",
                registerBtn: "Зарегистрироваться",
            },
            error: {
                empty: "Пожалуйста, заполните это поле!",
                testMin: "Тест должен содержать не менее 2 заданий!",
                testMax: "Тест может содержать не более 10 заданий!",
                loginPassword: "Неверный логин или пароль!",
            },
            question: {
                lessonDelete: "Вы уверены, что хотите удалить этот урок?",
            },
            languages: {
                "en": "Английский",
                "gr": "Немецкий",
                "fr": "Французский",
                "ru": "Русский",
                "ch": "Китайский",
                "jp": "Японский",
            },
            lessonLang: {
                "English": "Английский",
                "German": "Немецкий",
                "French": "Французский",
                "Russian": "Русский",
                "Chinese": "Китайский",
                "Japanese": "Японский",
            },
            categories: {
                reading: "чтение",
                grammar: "грамматика",
                speaking: "говорение",
            },
            rating: {
                high: "Высокий рейтинг",
                low: "Низкий рейтинг",
            },
            menu: {
                home: "Главная",
                lessons: "Уроки",
                authors: "Авторы",
                create: "Создать",
                profile: "Профиль",
                logout: "Выход",
                login: "Вход",
                registration: "Регистрация",
                feedback: "Отзывы",
            },
            home: {
                title: "Расширьте своё представление об изучении языков",
                titleText: "Упростите изучение иностранных языков с помощью нашей платформы, что предлагает широкий спектр уроков, тестов и общение с другими пользователями.",
                features: {
                    lessons: {
                        title: "Множество уроков",
                        text: "На нашей платформе мы предлагаем множество уроков по изучению различных языков. Здесь вы непременно найдете что-нибудь интересное.",
                    },
                    tests: {
                        title: "Практические тесты",
                        text: "Многие уроки дополняются практическими тестами. Таким образом, вы можете начать использовать свои теоретические знания немедленно.",
                    },
                    creation: {
                        title: "Простота создания",
                        text: "Создавайте новый контент легко и беспрепятственно с помощью нашего готового шаблона. Это даст вам возможность проявить свой творческий потенциал.",
                    },
                },
                policy: {
                    text: "Используя сайт, вы соглашаетесь с нашей политикой конфиденциальности.",
                    call: "Подробнее.",
                },
                callToAction: {
                    title: "Начни уже сейчас",
                    text: "Быстро создавайте собственные уроки, находите и решайте чужие, делитесь своим мнением в разделе комментариев и выражайте, насколько вам понравился контент автора. Не ждите завтрашнего дня, начинайте прямо сейчас!",
                },
                feedback: {
                    title: "Отзывы пользователей",
                    question: "Имеете мнение о нашей платформе?",
                },
            },
            policy: {
                scope: {
                    title: "1. ОБЛАСТЬ ПРИМЕНЕНИЯ",
                    body: "Данная Политика конфиденциальности и использования cookies объясняет, как RLang ('мы', 'нас', 'наш' или 'Компания') собирает, обрабатывает, использует и защищает персональные данные пользователей ('вы', 'ваш' или 'Пользователь') нашего веб-приложения для изучения языков (далее 'Сервис').",
                },
                basis: {
                    title: "2. ПРАВОВОЕ ОСНОВАНИЕ ДЛЯ ОБРАБОТКИ ДАННЫХ",
                    body: "Мы обрабатываем ваши персональные данные на следующих правовых основаниях:",
                    items: [
                        "Исполнение контракта: Обработка ваших учетных данных для входа, имени, фамилии и адреса электронной почты необходима для предоставления вам доступа к нашему Сервису и управления вашей учетной записью.",
                        "Законные интересы: Мы можем обрабатывать данные в целях безопасности, предотвращения мошенничества, улучшения Сервиса и анализа бизнеса, если ваши права не перевешивают эти интересы.",
                        "Согласие: Если того требует закон, мы полагаемся на ваше явное согласие, в частности для использования файлов-cookie.",
                        "Правовое обязательство: Мы обрабатываем данные для соблюдения применимого законодательства.",
                    ],
                },
                data: {
                    title: "3. СОБИРАЕМЫЕ ПЕРСОНАЛЬНЫЕ ДАННЫЕ",
                    body: "Мы собираем и обрабатываем следующие персональные данные:",
                    items: [
                        "Имя пользователя (логин) - Account creation and authentication",
                        "Пароль - Безопасность учетной записи (зашифрован/хеширован)",
                        "Имя и Фамилия - Персонализация и идентификация",
                        "Адрес электронной почты - уведомления, коммуникация",
                        "IP-адрес - Безопасность, обнаружение мошенничества, аналитика Сервиса",
                    ],
                },
                usage: {
                    title: "4. КАК МЫ ИСПОЛЬЗУЕМ ВАШИ ДАННЫЕ",
                    body: "Мы используем ваши персональные данные в следующих целях:",
                    items: [
                        "Создание и управление вашей учетной записью",
                        "Предоставление, обслуживание и улучшение Сервиса",
                        "Отправка сообщений, связанных с Сервисом (например, восстановление пароля, обновления)",
                        "Обнаружение и предотвращение мошенничества, злоупотреблений и инцидентов безопасности",
                        "Ответы на ваши запросы",
                        "Соблюдение правовых обязательств",
                    ],
                },
                sharing: {
                    title: "5. ПЕРЕДАЧА ВАШИХ ДАННЫХ",
                    body: "Мы не продаем, не сдаем в аренду и не передаем ваши персональные данные третьим лицам в маркетинговых целях. Мы можем раскрыть ваши данные в следующих случаях:",
                    items: [
                        "Поставщики услуг: Поставщикам, которые предоставляют важные услуги (хостинг, электронная почта, аналитика) в соответствии с соглашениями об обработке данных",
                        "Требования закона: Когда того требует закон, судебное решение или требование государственного органа",
                        "Передача бизнеса: В случае слияния, поглощения или продажи активов",
                        "Согласие пользователя: С вашим явным согласием на передачу определенным третьим лицам",
                    ],
                },
                transfers: {
                    title: "6. МЕЖДУНАРОДНАЯ ПЕРЕДАЧА ДАННЫХ",
                    body: "Если ваши данные передаются за пределы ЕЭЗ, мы обеспечиваем надлежащие гарантии посредством:",
                    items: [
                        "Стандартных договорных оговорок (SCC)",
                        "Решений об адекватности Европейской комиссии",
                        "Вашего явного согласия",
                    ],
                }
            }
        },
    },
}