export const Common = {
    url: "http://localhost:8000",
    networkErrorMsg: "Something went wrong. Try again later.",
    authErrorMsg: "You have to login first!",
    lines: {
        en: {
            title: {
                username: "Username",
                name: "Name",
                surname: "Surname",
                password: "Password",
                mainFeatures: "Main Features",
                feedbackPopUp: "Feedback",
                lessons: "LESSONS",
                categories: "CATEGORIES",
                languages: "LANGUAGES",
                deleteion: "Deletion",
                author: "Author",
                login: "Login",
                feedbackPage: "ADMIN",
            },
            placeholder: {
                commentInput: "Your comment...",
                feedbackInput: "Your feedback...",
                login: "Your username...",
                password: "Your password...",
            },
            button: {
                saveBtn: "Save",
                signIn: "Sign in",
                signUp: "Sign up",
                createLesson: "Create lesson",
                seeLessons: "See lessons",
                findTests: "Find tests",
                feedbackBtn: "Leave feedback",
                cancelBtn: "Cancel",
                sendBtn: "Save",
                deleteBtn: "Delete",
                studyBtn: "Study",
                loginBtn: "Login",
            },
            error: {
                empty: "Please, fill this field!",
                testMin: "Test has to include at least 2 tasks!",
                testMax: "Test can contain no more than 10 tasks!",
                loginPassword: "Incorrect login or password!",
            },
            question: {
                lessonDelete: "Are you sure you want to delete this lesson?",
            },
            languages: {
                "en": "English",
                "gr": "German",
                "fr": "French",
                "ru": "Russian",
                "ch": "Chinese",
                "jp": "Japanese",
            },
            categories: {
                reading: "reading",
                grammar: "grammar",
                speaking: "speaking",
            },
            menu: {
                home: "Home",
                lessons: "Lessons",
                authors: "Authors",
                create: "Create",
                profile: "Profile",
                logout: "Logout",
                login: "Login",
                registration: "Registration",
                feedback: "Feedback",
            },
            home: {
                title: "Expand your horizons in terms of language learning",
                titleText: "Make it simple to learn foreign languages with our platform, which offers wide range of different lessons, practical tests, regular content updates and social communication with outher learners.",
                features: {
                    lessons: {
                        title: "Many lessons",
                        text: "We suggest many lessons of different languages on our platform. We believe that you'll definitely find something for yourself.",
                    },
                    tests: {
                        title: "Practical tests",
                        text: "Many lessons offers practical tests in addition to their contents. So you can start using your theoretical knowledge immediately.",
                    },
                    creation: {
                        title: "Ease of creation",
                        text: "Create new content easily and painless with our predefined layout. It'll give you a lot possibilities to express your creativity.",
                    },
                },
                callToAction: {
                    title: "Start learning now",
                    text: "Quickly design your own lessons, find and solve somebody's else, share your opinion in the comment section, and express how much you've liked creator's content by liking it.\nDon't wait for a tomorrow, start now!",
                },
                feedback: {
                    title: "User's feedback",
                    question: "Have an opinion on our platform?",
                },
            }
        },
        gr: {
            title: {
                username: "Benutzernamen",
                name: "Name",
                surname: "Familienname",
                password: "Passwort",
                mainFeatures: "Hauptmerkmal",
                feedbackPopUp: "Feedback",
                lessons: "LEHREN",
                categories: "KATEGORIEN",
                languages: "SPRACHE",
                deleteion: "Löschung",
                author: "Autor",
                login: "Login",
                feedbackPage: "ADMIN",
            },
            placeholder: {
                commentInput: "Ihr Kommentar...",
                feedbackInput: "Ihr Feedback...",
                login: "Ihr Benutzername...",
                password: "Ihr Passwort...",
            },
            button: {
                saveBtn: "Speichern",
                signIn: "Anmelden",
                signUp: "Registrierung",
                createLesson: "Lektion erstellen",
                seeLessons: "Feedback hinterlassen",
                findTests: "Tests finden",
                feedbackBtn: "Laisser des commentaires",
                cancelBtn: "Stornieren",
                sendBtn: "Speichern",
                deleteBtn: "Löschen",
                studyBtn: "Studie",
                loginBtn: "Login",
            },
            error: {
                empty: "Bitte füllen Sie dieses Feld aus!",
                testMin: "Der Test muss mindestens 2 Aufgaben enthalten!",
                testMax: "Der Test kann nicht mehr als 10 Aufgaben enthalten!",
                loginPassword: "Falsches Login oder Passwort!",
            },
            question: {
                lessonDelete: "Sind Sie sicher, dass Sie diese Lektion löschen möchten?",
            },
            languages: {
                "en": "Englischsprachig",
                "gr": "Deutsch",
                "fr": "Französisch",
                "ru": "Russisch",
                "ch": "Chinesisch",
                "jp": "Japanisch",
            },
            categories: {
                reading: "lesung",
                grammar: "grammatik",
                speaking: "sprechen",
            },
            menu: {
                home: "Startseite",
                lessons: "Lehren",
                authors: "Autor",
                create: "Erstellen",
                profile: "Profil",
                logout: "Abmelden",
                login: "Login",
                registration: "Registrierung",
                feedback: "Feedback",
            },
            home: {
                title: "Erweitern Sie Ihren Horizont in Bezug auf das Sprachenlernen",
                titleText: "Erleichtern Sie das Erlernen von Fremdsprachen mit unserer Plattform, die eine breite Palette verschiedener Lektionen, praktischer Tests und sozialer Kommunikation mit anderen Lernenden bietet.",
                features: {
                    lessons: {
                        title: "Viele Lektionen",
                        text: "Wir schlagen auf unserer Plattform viele Lektionen in verschiedenen Sprachen vor. Wir glauben, dass Sie auf jeden Fall etwas für sich finden werden.",
                    },
                    tests: {
                        title: "Praxistest",
                        text: "Viele Lektionen bieten zusätzlich zu ihren Inhalten praktische Tests an. So können Sie Ihr theoretisches Wissen sofort anwenden.",
                    },
                    creation: {
                        title: "Leichtigkeit der Schöpfung",
                        text: "Erstellen Sie neue Inhalte einfach und schmerzlos mit unserem vordefinierten Layout. Es gibt Ihnen viele Möglichkeiten, Ihre Kreativität auszudrücken.",
                    },
                },
                callToAction: {
                    title: "Jetzt starten",
                    text: "Entwerfen Sie schnell Ihre eigenen Lektionen, finden und lösen Sie die von jemand anderem, teilen Sie Ihre Meinung im Kommentarbereich mit und drücken Sie aus, wie sehr Ihnen der Inhalt des Erstellers gefallen hat. Warte nicht auf ein Morgen, fang jetzt an!",
                },
                feedback: {
                    title: "Benutzer-Feedback",
                    question: "Haben Sie eine Meinung zu unserer Plattform?",
                },
            },
        },
        fr: {
            title: {
                username: "Nom d'utilisateur",
                name: "Nom",
                surname: "Nom de Famille",
                password: "Mot de Passe",
                mainFeatures: "Caractéristiques Principales",
                feedbackPopUp: "Commentaires",
                lessons: "LEÇONS",
                categories: "CATÉGORIES",
                languages: "LANGUES",
                deleteion: "Suppression",
                author: "Auteur",
                login: "Connexion",
                feedbackPage: "ADMIN",
            },
            placeholder: {
                commentInput: "Votre commentaire...",
                feedbackInput: "Vos commentaires...",
                login: "Votre nom d'utilisateur...",
                password: "Votre mot de passe...",
            },
            button: {
                saveBtn: "Sauvegarder",
                signIn: "Se connecter",
                signUp: "S'inscrire",
                createLesson: "Créer une leçon",
                seeLessons: "Voir les leçons",
                findTests: "Trouver des tests",
                feedbackBtn: "Laisser des commentaires",
                cancelBtn: "Annuler",
                sendBtn: "Sauvegarder",
                deleteBtn: "Supprimer",
                studyBtn: "Étude",
                loginBtn: "Connexion",
            },
            error: {
                empty: "Veuillez remplir ce champ!",
                testMin: "Le test doit inclure au moins 2 tâches!",
                testMax: "Le test ne peut pas contenir plus de 10 tâches!",
                loginPassword: "Identifiant ou mot de passe incorrect!",
            },
            question: {
                lessonDelete: "Êtes-vous sûr de vouloir supprimer cette leçon?",
            },
            languages: {
                "en": "Anglais",
                "gr": "Allemand",
                "fr": "Français",
                "ru": "Russe",
                "ch": "Chinois",
                "jp": "Japonais",
            },
            categories: {
                reading: "lecture",
                grammar: "grammaire",
                speaking: "parler",
            },
            menu: {
                home: "Accueil",
                lessons: "Leçons",
                authors: "Auteurs",
                create: "Créer",
                profile: "Profil",
                logout: "Déconnexion",
                login: "Connexion",
                registration: "Inscription",
                feedback: "Commentaires",
            },
            home: {
                title: "Élargir les horizons en termes d'apprentissage des langues",
                titleText: "Simplifiez l'apprentissage des langues étrangères avec notre plateforme, qui propose un large éventail de leçons différentes, des tests pratiques une communication sociale avec les apprenants extérieurs.",
                features: {
                    lessons: {
                        title: "De nombreuses leçons",
                        text: "Nous suggérons de nombreuses leçons de différentes langues sur notre plateforme. Vous trouverez certainement quelque chose pour vous-même.",
                    },
                    tests: {
                        title: "Tests pratiques",
                        text: "Les leçons proposent des tests pratiques en plus de leur contenu. Vous pouvez donc commencer à utiliser vos nouvelles connaissances immédiatement.",
                    },
                    creation: {
                        title: "Facilité de création",
                        text: "Créez de nouveaux contenus facilement et sans douleur avec notre mise en page prédéfinie. Cela vous laissera beaucoup de possibilités d'exprimer votre créativité.",
                    },
                },
                callToAction: {
                    title: "Commencez ici",
                    text: "Concevez rapidement vos propres leçons, trouvez et résolvez celles de quelqu'un d'autre, partagez votre opinion dans la section des commentaires et exprimez à quel point vous avez aimé le contenu du créateur. N'attendez pas demain, commencez maintenant!",
                },
                feedback: {
                    title: "Commentaires de l'utilisateur",
                    question: "Vous avez un avis sur notre plateforme?",
                },
            }
        },
        ru: {
            title: {
                username: "Логин",
                name: "Имя",
                surname: "Фамилия",
                password: "Пароль",
                mainFeatures: "Основные преимущества",
                feedbackPopUp: "Обратная связь",
                lessons: "УРОКИ",
                categories: "КАТЕГОРИИ",
                languages: "ЯЗЫКИ",
                deleteion: "Удаление",
                author: "Автор",
                login: "Авторизация",
                feedbackPage: "АДМИН",
            },
            placeholder: {
                commentInput: "Ваш комментарий...",
                feedbackInput: "Ваш отзыв...",
                login: "Ваш логин...",
                password: "Ваш пароль...",
            },
            button: {
                saveBtn: "Сохранить",
                signIn: "Вход",
                signUp: "Регистрация",
                createLesson: "Создать урок",
                seeLessons: "Все уроки",
                findTests: "Найти тест",
                feedbackBtn: "Оставить отзыв",
                cancelBtn: "Отмена",
                sendBtn: "Отправить",
                deleteBtn: "Удалить",
                studyBtn: "Изучить",
                loginBtn: "Войти",
            },
            error: {
                empty: "Пожалуйста, заполните это поле!",
                testMin: "Тест должен содержать не менее 2 заданий!",
                testMax: "Тест может содержать не более 10 заданий!",
                loginPassword: "Неверный логин или пароль!",
            },
            question: {
                lessonDelete: "Вы уверены, что хотите удалить этот урок?",
            },
            languages: {
                "en": "Английский",
                "gr": "Немецкий",
                "fr": "Французский",
                "ru": "Русский",
                "ch": "Китайский",
                "jp": "Японский",
            },
            categories: {
                reading: "чтение",
                grammar: "грамматика",
                speaking: "говорение",
            },
            menu: {
                home: "Главная",
                lessons: "Уроки",
                authors: "Авторы",
                create: "Создать",
                profile: "Профиль",
                logout: "Выход",
                login: "Вход",
                registration: "Регистрация",
                feedback: "Отзывы",
            },
            home: {
                title: "Расширьте своё представление об изучении языков",
                titleText: "Упростите изучение иностранных языков с помощью нашей платформы, что предлагает широкий спектр уроков, тестов и общение с другими пользователями.",
                features: {
                    lessons: {
                        title: "Множество уроков",
                        text: "На нашей платформе мы предлагаем множество уроков по изучению различных языков. Здесь вы непременно найдете что-нибудь интересное.",
                    },
                    tests: {
                        title: "Практические тесты",
                        text: "Многие уроки дополняются практическими тестами. Таким образом, вы можете начать использовать свои теоретические знания немедленно.",
                    },
                    creation: {
                        title: "Простота создания",
                        text: "Создавайте новый контент легко и беспрепятственно с помощью нашего готового шаблона. Это даст вам возможность проявить свой творческий потенциал.",
                    },
                },
                callToAction: {
                    title: "Начни уже сейчас",
                    text: "Быстро создавайте собственные уроки, находите и решайте чужие, делитесь своим мнением в разделе комментариев и выражайте, насколько вам понравился контент автора. Не ждите завтрашнего дня, начинайте прямо сейчас!",
                },
                feedback: {
                    title: "Отзывы пользователей",
                    question: "Имеете мнение о нашей платформе?",
                },
            },
        },
    },
}