# Generated by Django 6.0.3 on 2026-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
    ]
