# Generated by Django 6.0.3 on 2026-03-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_myuser_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
