# Generated by Django 6.0.3 on 2026-03-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_rename_is_stuff_myuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
