# Generated by Django 6.0.3 on 2026-03-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0006_myuser_avatar_myuser_bio_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
    ]
