# Generated by Django 6.0.3 on 2026-03-19 12:37

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0008_alter_myuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.user.models.get_avatar_upload_path),
        ),
    ]
