# Generated by Django 6.0.3 on 2026-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0009_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
