# Generated by Django 6.0.3 on 2026-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_lesson', '0006_lesson_created_lesson_updated_solvedlesson'),
        ('core_user', '0010_myuser_created_myuser_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='lessons_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='core_lesson.lesson'),
        ),
    ]
