# Generated by Django 6.0.3 on 2026-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0011_alter_myuser_lessons_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='language',
            field=models.IntegerField(choices=[(1, 'en'), (2, 'gr'), (3, 'fr'), (4, 'ru')], default=1),
        ),
    ]
