# Generated by Django 6.0.3 on 2026-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0013_alter_myuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('gr', 'gr'), ('fr', 'fr'), ('ru', 'ru')], default='en', max_length=2),
        ),
    ]
